FROM node:14.17.1-alpine3.13
WORKDIR /app

ARG NPM_CONFIG__AUTH

COPY package.json yarn.lock jsconfig.json craco.config.js ant.theme.js ./
COPY public/  ./public/
COPY src/  ./src/

ARG GIT_COMMIT
ARG GIT_VERSION
ARG REACT_APP_SUPPORT_EMAIL
ARG REACT_APP_SUPPORT_PHONE_NUMBER
ENV NODE_ENV=development
ENV PORT=8080
ENV GIT_COMMIT $GIT_COMMIT
ENV GIT_VERSION $GIT_VERSION
ENV CHOKIDAR_USEPOLLING=true
ENV PUBLIC_URL=/health-department
ENV WDS_SOCKET_PATH=/health-department/sockjs-node
ENV REACT_APP_SUPPORT_EMAIL $REACT_APP_SUPPORT_EMAIL
ENV REACT_APP_SUPPORT_PHONE_NUMBER $REACT_APP_SUPPORT_PHONE_NUMBER

EXPOSE 8080
CMD yarn install --mutex file:/usr/local/share/.cache/yarn/.yarn-mutex && yarn start
