export const POSITIVE_TEST_RESULT = 'POSITIVE';
export const NEGATIVE_TEST_RESULT = 'NEGATIVE';
export const UNKNOWN_TEST_RESULT = 'UNKNOWN';

export const PCR_COVID_TEST_TYPE = 'PCR';
export const FAST_COVID_TEST_TYPE = 'FAST';
export const UNKNOWN_COVID_TEST_TYPE = 'UNKNOWN';
