export const BADGE_SIGNATURE_PUBLIC_KEY_BASE64_V3 =
  'BJhA/0GVMqiM7/HNrZ3xFP+LDIGKIOkc1ybCTmWzBKRVMZsVKWUBhDxuiNOaPqHxXn/5zNistW8jEZjvmhhXYFA=';
export const BADGE_SIGNATURE_PUBLIC_KEY_BASE64_V4 =
  'BIzE8FlvWCTM9h0OtB8iNPh2KHa4e63q7CnBrM6mbNbguV5QVIF3jG0pWHgvucdCH/LrSva/Qk7RGq9BmIlTT78=';
