FROM node:14.17.3-alpine3.14

# set timezone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
ENV NODE_ENV=test

# install dependencies
ARG NPM_CONFIG__AUTH
COPY package.json yarn.lock .npmrc .yarnrc ./
RUN yarn install --check-files && yarn cache clean

# copy source files
COPY * ./
COPY config/  ./config/
COPY src/  ./src/
COPY ci/  ./ci/

CMD ["sh"]
