FROM node:14.17.3-alpine3.14
WORKDIR /app

ARG GIT_COMMIT
ARG GIT_VERSION
ARG NPM_CONFIG__AUTH
ENV NODE_ENV=test

COPY package.json yarn.lock .npmrc .yarnrc ./
RUN yarn install --check-files && yarn cache clean
RUN yarn licenses generate-disclaimer > ./licenses-full.txt
RUN echo "{\"commit\":\"$GIT_COMMIT\", \"version\":\"$GIT_VERSION\"}" >> version.json

COPY * ./
COPY config/  ./config/
COPY src/  ./src/
COPY ci/  ./ci/

CMD ["sh"]
