paths:
  /auth/login:
    post:
      operationId: post-auth-login
      tags:
        - Auth
      summary: Log in as a venue operator
      description:
        'Login as a [Venue
        Operator](https://luca-app.de/securityconcept/properties/actors.html#term-Venue-Owner).'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: luca@nexenio.com
                password:
                  type: string
                  default: testing
              required:
                - username
                - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
            text/plain:
              schema:
                type: object
                properties: {}
          headers:
            Set-Cookie:
              schema:
                type: string
              description: connect.sid
        '400':
          $ref: '#/components/schemas/BadRequest'
        '403':
          description: Username and Password combination does not match
        '423':
          description: The account has not been activated.
        '429':
          $ref: '#/components/schemas/TooManyRequestsMinute'
  /auth/healthDepartmentEmployee/login:
    post:
      tags:
        - Auth
      operationId: post-auth-healthDepartmentEmployee-login
      summary: Log in as a health department employee
      description:
        'Log in as a [health
        department](https://luca-app.de/securityconcept/properties/actors.html#term-Health-Department)
        employee.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: luca@nexenio.com
                password:
                  type: string
                  default: testing
              required:
                - username
                - password
        description: ''
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          description: Username and Password combination does not match
        '429':
          $ref: '#/components/schemas/TooManyRequestsMinute'
    parameters: []
  /auth/logout:
    post:
      tags:
        - Auth
      summary: 'Log out, deleting the current session'
      description: 'Log out, deleting the current session.'
      operationId: post-auth-logout
      responses:
        '204':
          description: No Content
  /auth/me:
    get:
      tags:
        - Auth
      summary: Get the current user
      operationId: get-auth-me
      description:
        Returns the current user (venue operator or health department employee).
      parameters:
        - schema:
            type: string
          in: cookie
          name: connect.sid
          description: The session ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  operatorId:
                    type: string
                    minLength: 1
                  username:
                    type: string
                    minLength: 1
                  firstName:
                    type: string
                    minLength: 1
                  lastName:
                    type: string
                    minLength: 1
                  publicKey:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  avvAccepted:
                    type: boolean
                  lastVersionSeen:
                    type: string
                    minLength: 1
                required:
                  - operatorId
                  - username
                  - firstName
                  - lastName
                  - publicKey
                  - email
              examples:
                Operator:
                  value:
                    operatorId: b92d1fee-d21b-4e56-bc0c-d5ef5517e17a
                    username: luca@nexenio.com
                    firstName: Marty
                    lastName: Labadie
                    publicKey: BIFmPvOhr2shd2FKFrmiZcFIF3W8aWRa3xRAV1xUpP5HrR1VvYG/SjFM1A6YZyyNlmlKEwVd+/mZwmUlk7RU+i4=
                    email: luca@nexenio.com
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
  /auth/healthDepartmentEmployee/me:
    get:
      summary: Get the current user (health department employee)
      description: Returns the current user (health department employee).
      tags:
        - Auth
      operationId: get-auth-healthDepartmentEmployee-me
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  employeeId:
                    type: string
                    minLength: 1
                  firstName:
                    type: string
                    minLength: 1
                  lastName:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  departmentId:
                    type: string
                    minLength: 1
                  isAdmin:
                    type: boolean
                  deletedAt:
                    type: integer
                  isTrusted:
                    type: boolean
                required:
                  - employeeId
                  - firstName
                  - lastName
                  - email
                  - departmentId
                  - isAdmin
                  - isTrusted
              examples:
                Health department employee:
                  value:
                    employeeId: f7ee6624-1b19-45c4-ad14-dd8382787a09
                    firstName: Felix
                    lastName: McCullough
                    email: luca@nexenio.com
                    departmentId: b764123d-7f3e-44d4-a64f-630ab0f9391d
                    isAdmin: true
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
