paths:
  '/badgeRegistrators/{registratorId}':
    get:
      tags: [BadgeRegistrators]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  uuid:
                    type: string
                    minLength: 1
                    format: uuid
                  name:
                    type: string
                    minLength: 1
                  createdAt:
                    type: string
                    minLength: 1
                  updatedAt:
                    type: string
                    minLength: 1
                required:
                  - uuid
                  - name
                  - createdAt
                  - updatedAt
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Badge Registrator not found
      operationId: get-badgeRegistrators
      description: Get a single badge registrator
    parameters:
      - schema:
          type: string
          format: uuid
        name: registratorId
        in: path
        required: true
