paths:
  /badges/:
    post:
      summary: Create badge user
      operationId: post-users-badge
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  signature:
                    type: string
        '400':
          $ref: '#/components/schemas/BadRequest'
        '403':
          description: Signature not valid
        '409':
          description: User already present
      tags:
        - Users
      parameters:
        - in: header
          name: Badge-Generator-Authorization
          description: Bearer token.
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                publicKey:
                  type: string
