paths:
  '/forms/{formId}':
    get:
      summary: Get form content
      tags:
        - Forms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  groupName:
                    type: string
                    minLength: 1
                  locationName:
                    type: string
                  name:
                    type: string
                    minLength: 1
                  scannerId:
                    type: string
                    minLength: 1
                  locationId:
                    type: string
                    minLength: 1
                  publicKey:
                    type: string
                    minLength: 1
                  endsAt:
                    type: string
                  tableCount:
                    type: integer
                required:
                  - groupName
                  - name
                  - scannerId
                  - locationId
                  - publicKey
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Location not found
        '410':
          description: Locations operator already deleted
      operationId: get-forms-formid
      description: Get form content.
    parameters:
      - schema:
          type: string
        name: formId
        in: path
        required: true
