components:
  schemas:
    EncryptedKeyPair:
      title: EncryptedKeyPair
      type: object
      required:
        - healthDepartmentId
        - data
        - iv
        - mac
        - publicKey
        - signature
      properties:
        healthDepartmentId:
          type: string
          minLength: 1
        data:
          type: string
          minLength: 1
        iv:
          type: string
          minLength: 1
        mac:
          type: string
          minLength: 1
        publicKey:
          type: string
          minLength: 1
        signature:
          type: string
          minLength: 1
      description: Public key and private key encrypted for a health department.
