paths:
  /healthDepartments/keys:
    get:
      summary: Retrieve keys
      description:
        "Get the current user's [health
        department](https://luca-app.de/securityconcept/properties/actors.html#term-Health-Department)'s
        public keys."
      tags:
        - HealthDepartments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publicHDEKP:
                    type: string
                    nullable: true
                  publicHDSKP:
                    type: string
                    nullable: true
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
        '404':
          description: Department not found
    post:
      summary: Post key pair
      tags:
        - HealthDepartments
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
        '403':
          description: 'Forbidden, e.g., when updating before expiration.'
        '404':
          description: Department Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                publicHDEKP:
                  type: string
                publicHDSKP:
                  type: string
  /healthDepartments/region:
    get:
      summary: Get department region and district
      tags:
        - HealthDepartments
      responses:
        '200':
          description: OK
    post:
      summary: Update region options used for SORMAS data export
      tags:
        - HealthDepartments
      responses:
        '204':
          description: No Content
        '404':
          description: Department Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                region:
                  type: string
                district:
                  type: string
  '/healthDepartments/{departmentId}':
    get:
      summary: Get department info by ID
      description:
        'Get [health
        department](https://luca-app.de/securityconcept/properties/actors.html#term-Health-Department)
        info by its UUID.'
      tags:
        - HealthDepartments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  departmentId:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  publicHDEKP:
                    type: string
                    nullable: true
                  publicHDSKP:
                    type: string
                    nullable: true
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Department not found
    parameters:
      - schema:
          type: string
          format: uuid
        name: departmentId
        in: path
        required: true
  '/healthDepartments/contact':
    patch:
      summary: Update contact information department
      tags:
        - HealthDepartments
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Department not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phone:
                  type: string
  /healthDepartments/privateKeySecret:
    get:
      summary: Get privateKeySecret
      description:
        Get privateKeySecret for the current user's health department.
      tags:
        - HealthDepartments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  privateKeySecret:
                    type: string
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
        '404':
          description: Department not found
