paths:
  /operators:
    post:
      tags:
        - Operators
      summary: Register a new operator
      operationId: post-locationTransfers
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '409':
          description: Operator already exists
        '429':
          $ref: '#/components/schemas/TooManyRequestsDay'
      description:
        Register a new operator. Needs to be confirmed via email link.
    patch:
      summary: Patch operator
      operationId: patch-operators
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The operator account has been deactivated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                avvAccepted:
                  type: boolean
                lastVersionSeen:
                  type: string
      tags:
        - Operators
    delete:
      summary: Request deletion of operator's account
      operationId: post-operators-deletionRequest
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
      tags:
        - Operators
  /operators/activate:
    post:
      tags:
        - Operators
      summary: Activate account
      operationId: post-operators-activate
      responses:
        '201':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Activation Mail or Operator not found
        '409':
          description: Activation Mail already closed
        '410':
          description: Activation Mail Link expired
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activationId:
                  type: string
                lang:
                  type: string
        description: ''
  /operators/publicKey:
    post:
      tags:
        - Operators
      summary: Update operator's public key
      operationId: post-operators-publicKey
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                publicKey:
                  type: string
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: Forbidden. The account might have been deactivated.
  /operators/privateKeySecret:
    get:
      summary: Get private key secret
      tags:
        - Operators
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  privateKeySecret:
                    type: string
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
      operationId: get-operators-privateKeySecret
  /operators/restore:
    post:
      tags:
        - Operators
      summary: Revoke deletion request of operator's account
      operationId: delete-operators-deletionRequest
      responses:
        '204':
          description: Success
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
