paths:
  '/scanners/{scannerId}':
    parameters:
      - schema:
          type: string
        name: scannerId
        in: path
        required: true
    get:
      summary: Get scanner information
      description:
        'Get
        [scanner](https://luca-app.de/securityconcept/properties/actors.html#term-Scanner-Frontend)
        information'
      tags:
        - Scanners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  scannerId:
                    type: string
                  locationId:
                    type: string
                  publicKey:
                    type: string
                required:
                  - scannerId
                  - locationId
                  - publicKey
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Location not found
        '410':
          description: Location already deleted
      operationId: get-scanners-scannerId
  '/scanners/{scannerAccessId}/traces/count/current':
    parameters:
      - schema:
          type: string
        name: scannerAccessId
        in: path
        required: true
    get:
      summary: Count of traces at location currently active
      tags:
        - Scanners
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  value: '9001'
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Location not found
      operationId: get-scanners-scannerId-traces-count-current
      description:
        "Count of currently active traces at the
        [scanner](https://luca-app.de/securityconcept/properties/actors.html#term-Scanner-Frontend)'s
        location."
  '/scanners/{scannerAccessId}/traces/count/total':
    parameters:
      - schema:
          type: string
        name: scannerAccessId
        in: path
        required: true
    get:
      summary: Count of traces at location
      tags:
        - Scanners
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  value: '9001'
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Location not found
      operationId: get-scanners-scannerId-traces-count-total
      description:
        "Count of all traces at the
        [scanner](https://luca-app.de/securityconcept/properties/actors.html#term-Scanner-Frontend)'s
        location"
  '/scanners/access/{scannerAccessId}':
    parameters:
      - schema:
          type: string
        name: scannerAccessId
        in: path
        required: true
    get:
      summary: Access information
      tags:
        - Scanners
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  groupName:
                    type: string
                    minLength: 1
                  locationName:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  scannerId:
                    type: string
                    minLength: 1
                  scannerAccessId:
                    type: string
                    minLength: 1
                  locationId:
                    type: string
                    minLength: 1
                  publicKey:
                    type: string
                    minLength: 1
                  endsAt:
                    type: string
                    minLength: 1
                  tableCount:
                    type: integer
                required:
                  - groupName
                  - name
                  - scannerId
                  - scannerAccessId
                  - locationId
                  - publicKey
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Location not found
        '410':
          description: Location already deleted
      operationId: get-scanners-access-scannerAccessId
