paths:
  /sms/request:
    post:
      summary: Request SMS challenge
      tags:
        - SMS
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  challengeId:
                    type: string
        '400':
          $ref: '#/components/schemas/BadRequest'
        '429':
          $ref: '#/components/schemas/TooManyRequestsMinute'
        '503':
          description: Provider Service unavailable
      operationId: post-sms-request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                challengeId:
                  type: string
      description: Get SMS challenge
  /sms/verify:
    post:
      summary: Verify SMS challenge
      tags:
        - SMS
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '403':
          description: Challenge not found
        '429':
          $ref: '#/components/schemas/TooManyRequestsDay'
      operationId: post-sms-verify
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                challengeId:
                  type: string
                tan:
                  type: string
      description: Verify SMS challenge
  /sms/verify/bulk:
    post:
      summary: Bulk verify SMS challenge
      tags:
        - SMS
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  challengeId:
                    type: string
        '204':
          description: Success (debug only)
        '400':
          $ref: '#/components/schemas/BadRequest'
        '403':
          description: Challenge not found
      operationId: post-sms-verify-bulk
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                challengeIds:
                  type: array
                  minItems: 1
                  maxItems: 10
                  items:
                    type: string
      description: Verify SMS challenge (bulk).
