paths:
  /supportedZipCodes:
    get:
      summary: Get all supported ZIP codes
      tags: [SupportedZipCodes]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties: {}
      operationId: get-supportedZipCodes
      description: Get all supported ZIP codes.
  '/supportedZipCodes/{zipCode}':
    parameters:
      - schema:
          type: string
        name: zipCode
        in: path
        required: true
    get:
      summary: Check if ZIP code is supported
      tags: [SupportedZipCodes]
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Zip Code not found
      operationId: get-supportedZipCodes-zipCode
      description: Check if ZIP code is supported.
