paths:
  /testProviders:
    get:
      summary: Get all Test Providers
      tags:
        - TestProvider
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: 'Provider'
                uniqueItems: true
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    publicKey:
                      type: string
                    fingerprint:
                      type: string
