paths:
  /timesync:
    get:
      summary: Get current server time
      tags: [Server Time]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  unix:
                    type: integer
      operationId: get-current-server-time
      description: Get current server time
