paths:
  /tracingProcesses:
    get:
      summary: Get tracing processes
      tags:
        - TracingProcesses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                uniqueItems: true
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      minLength: 1
                    userTransferId: {}
                    didRequestLocations:
                      type: boolean
                    isCompleted:
                      type: boolean
                    createdAt:
                      type: number
                    assignee:
                      type: object
                      properties:
                        uuid:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                    deletedAt:
                      type: integer
                  required:
                    - uuid
                    - didRequestLocations
                    - isCompleted
                    - createdAt
                    - assigneeId
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
      operationId: get-tracingProcesses
      description:
        Get tracing processes initiated by the user's health department.
  '/tracingProcesses/{tracingProcessId}':
    parameters:
      - schema:
          type: string
        name: tracingProcessId
        in: path
        required: true
    get:
      summary: Get tracing process information
      operationId: get-tracingProcesses-tracingProcessId
      responses:
        '204':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    minLength: 1
                  status:
                    type: integer
                  userTransferId:
                    type: string
                  didRequestLocations:
                    type: boolean
                  isCompleted:
                    type: boolean
                  createdAt:
                    type: integer
                  assignee:
                    type: object
                    properties:
                      uuid:
                        type: string
                        minLength: 1
                      firstName:
                        type: string
                        minLength: 1
                      lastName:
                        type: string
                        minLength: 1
                  deletedAt:
                    type: integer
                  required:
                    - uuid
                    - status
                    - userTransferId
                    - didRequestLocations
                    - isCompleted
                    - createdAt
                    - assignee
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
      tags:
        - TracingProcesses
      description: Get tracing process information.
    patch:
      summary: Update tracing process information
      operationId: patch-tracingProcesses-tracingProcessId
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
        '404':
          description: Tracing Process not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                didRequestLocations:
                  type: boolean
                isCompleted:
                  type: boolean
                assigneeId:
                  type: string
      tags:
        - TracingProcesses
      description: Update tracing process information.
    delete:
      summary: Delete Tracing Process
      tags:
        - TracingProcesses
      responses:
        204:
          description: Success
        400:
          $ref: '#/components/schemas/BadRequest'
        401:
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
        404:
          description: Tracing Process not found
  '/tracingProcesses/{tracingProcessId}/locationTransfers':
    parameters:
      - schema:
          type: string
        name: tracingProcessId
        in: path
        required: true
    get:
      summary: Get location transfers for a process
      tags:
        - TracingProcesses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                      minLength: 1
                    locationId:
                      type: string
                      minLength: 1
                    time:
                      type: array
                      minItems: 2
                      maxItems: 2
                      items:
                        type: integer
                    isCompleted:
                      type: boolean
                    contactedAt:
                      type: integer
                    deletedAt:
                      type: integer
                  required:
                    - locationId
                    - time
                    - isCompleted
                    - uuid
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
      operationId: get-tracingProcesses-tracingProcessId-locationTransfers
      description:
        Get location transfers for a process managed by the current user's
        health department.
