paths:
  /versions/apps/android:
    get:
      summary: Android version
      description: Android version.
      tags: [Versions]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  minimumVersion:
                    type: integer
  /versions/apps/ios:
    get:
      summary: iOS version
      description: iOS version.
      tags: [Versions]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  minimumVersion:
                    type: integer
  /versions/apps/lst:
    get:
      summary: luca signing tool version
      description: luca signing tool version.
      tags: [Versions]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  minimumVersion:
                    type: integer
