const DEVICE_TYPE_IOS = 0;
const DEVICE_TYPE_ANDROID = 1;
const DEVICE_TYPE_STATIC = 2;
const DEVICE_TYPE_WEBAPP = 3;
const DEVICE_TYPE_FORM = 4;

module.exports = {
  DEVICE_TYPE_IOS,
  DEVICE_TYPE_ANDROID,
  DEVICE_TYPE_STATIC,
  DEVICE_TYPE_WEBAPP,
  DEVICE_TYPE_FORM,
};
