paths:
  '/locations/additionalDataSchema/{locationId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
    get:
      summary: Get additional data schemas
      tags:
        - Locations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    key:
                      type: string
                    label:
                      type: string
                    isRequired:
                      type: boolean
        '400':
          $ref: '#/components/schemas/BadRequest'
      operationId: get-locations-additionalDataSchema-locationId
      description: Get additional data schemas for the location.
    post:
      summary: Create new
      description: Create new additional data schema.
      operationId: post-locations-additionalDataSchema-locationId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  label:
                    type: string
                  uuid:
                    type: string
                  isRequired:
                    type: boolean
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
        description: The account has been deactivated
        '404':
          description: Location not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                label:
                  type: string
                isRequired:
                  type: string
      tags:
        - Locations
  '/locations/additionalDataSchema/{additionalDataId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: additionalDataId
        in: path
        required: true
    patch:
      summary: Change schema
      operationId: patch-locations-additionalDataSchema-additionalDataId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The account has been deactivated
        '404':
          description: Additional Data not found
      tags:
        - Locations
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                label:
                  type: string
                isRequired:
                  type: string
    delete:
      summary: Delete schema
      operationId: delete-locations-additionalDataSchema-additionalDataId
      tags:
        - Locations
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The account has been deactivated
        '404':
          description: Additional Data not found
