paths:
  /operators/email:
    parameters: []
    patch:
      tags:
        - Operators
      summary: Update email and language
      operationId: patch-operators-email
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The account has been deactivated
        '409':
          description: Email is already in use
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                lang:
                  type: string
      description: Changes need to be confirmed by email.
  /operators/email/isChangeActive:
    get:
      summary: Get change status of email change
      tags:
        - Operators
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The account has been deactivated
        '404':
          description: Email Change process not found
      operationId: get-operators-email-isChangeActive
      description: Get status of email change.
  '/operators/email/{email}':
    parameters:
      - schema:
          type: string
        name: email
        in: path
        required: true
    get:
      summary: Check if email is already registered
      tags:
        - Operators
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Email not found
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      operationId: get-operators-email-email
      description: Check if email is already registered for a venue operator.
  /operators/email/confirm:
    post:
      tags:
        - Operators
      summary: Activate an email
      operationId: post-operators-email-confirm
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '403':
          description: The account has been deactivated
        '404':
          description: Email not found
        '409':
          description: Email already confirmed
        '410':
          description: Email confirmation expired
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activationId:
                  type: string
