paths:
  /operators/locations:
    get:
      summary: List locations
      tags:
        - Operators
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
      operationId: get-operators-locations
    post:
      summary: Add location
      operationId: post-operators-locations
      responses:
        '201':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The operator account has been deactivated
        '404':
          description: Group not found
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                groupId:
                  type: string
                  minLength: 1
                locationName:
                  type: string
                  minLength: 1
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                phone:
                  type: string
                  minLength: 1
                streetName:
                  type: string
                  minLength: 1
                streetNr:
                  type: string
                  minLength: 1
                zipCode:
                  type: string
                  minLength: 1
                city:
                  type: string
                  minLength: 1
                state:
                  type: string
                  minLength: 1
                lat:
                  type: number
                lng:
                  type: number
                radius:
                  type: number
                tableCount:
                  type: number
                additionalData:
                  type: array
                  uniqueItems: true
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                        minLength: 1
                      label:
                        type: string
                        minLength: 1
                      isRequired:
                        type: boolean
                    required:
                      - key
                      - label
                      - isRequired
                type:
                  type: string
              required:
                - groupId
                - locationName
                - phone
                - streetName
                - streetNr
                - zipCode
                - city
      tags:
        - Operators
  '/operators/locations/{locationId}':
    parameters:
      - schema:
          type: string
        name: locationId
        in: path
        required: true
    get:
      summary: Get a specific location
      tags:
        - Operators
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '404':
          description: Location not found
      operationId: get-operators-locations-locationId
    patch:
      summary: Patch
      operationId: patch-operators-locations-locationId
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The operator account has been deactivated
        '404':
          description: Location not found
        '409':
          description: Location name not unique inside group
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                locationName:
                  type: string
                  minLength: 1
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                phone:
                  type: string
                  minLength: 1
                tableCount:
                  type: number
                radius:
                  type: number
                isIndoor:
                  type: boolean
      tags:
        - Operators
    delete:
      summary: Delete
      operationId: delete-operators-locations-locationId
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The operator account has been deactivated
        '404':
          description: Location not found
      tags:
        - Operators
  '/operators/locations/{locationId}/check-out':
    parameters:
      - schema:
          type: string
        name: locationId
        in: path
        required: true
    post:
      summary: Check out all current traces
      operationId: post-operators-locations-locationId-check-out
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description: The operator account has been deactivated
        '404':
          description: Location not found
      tags:
        - Operators
