paths:
  /operators/password/forgot:
    post:
      tags:
        - Operators
      summary: ''
      operationId: post-operators-password-forgot
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Operator with the email does not exist
        '412':
          description: Operator with the email is not activated
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                lang:
                  type: string
  /operators/password/change:
    post:
      tags:
        - Operators
      summary: Request password reset e-mail
      operationId: post-operators-password-change
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeOperator'
        '403':
          description:
            Current Password is not correct or the account might have been
            deactivated.
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
                lang:
                  type: string
              required:
                - currentPassword
                - newPassword
                - lang
      description: ''
    parameters: []
  /operators/password/reset:
    post:
      tags:
        - Operators
      summary: ''
      operationId: post-operators-password-reset
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Operator or Reset Request not found or expired
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resetId:
                  type: string
                newPassword:
                  type: string
  '/operators/password/reset/{resetId}':
    parameters:
      - schema:
          type: string
        name: resetId
        in: path
        required: true
    get:
      tags:
        - Operators
      summary: Get password reset information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  uuid:
                    type: string
                    minLength: 1
                  operatorId:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  closed:
                    type: boolean
                  createdAt:
                    type: string
                    minLength: 1
                  updatedAt:
                    type: string
                    minLength: 1
                required:
                  - uuid
                  - operatorId
                  - email
                  - closed
                  - createdAt
                  - updatedAt
        '400':
          $ref: '#/components/schemas/BadRequest'
        '404':
          description: Reset request not found or expired
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      operationId: get-operators-password-reset-resetId
      description: ''
