paths:
  /healthDepartmentEmployees/password/change:
    post:
      tags:
        - HealthDepartmentEmployees
      summary: Change password
      operationId: post-healthDepartmentEmployees-password-change
      responses:
        '204':
          description: Success
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployee'
        '403':
          description: Current Password is not correct
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      description: Change password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string

              required:
                - currentPassword
                - newPassword
  /healthDepartmentEmployees/password/renew:
    patch:
      tags:
        - HealthDepartmentEmployees
      summary: Renew password of employee
      operationId: patch-healthDepartmentEmployees-password-renew
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/schemas/BadRequest'
        '401':
          $ref: '#/components/schemas/RequiredUserOfTypeHealthDepartmentEmployeeAdmin'
        '403':
          description: Department does not match
        '429':
          $ref: '#/components/schemas/TooManyRequestsHour'
      description: Renew password of employee.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeId:
                  type: string

              required:
                - employeeId
