export const SELECT_DEVICE_ROLE_STEP = 'SELECT_DEVICE_ROLE_STEP';
export const DEVICE_AUTHENTICATION_QR_CODE_STEP =
  'DEVICE_AUTHENTICATION_QR_CODE_STEP';
export const DEVICE_AUTHENTICATION_ENCRYPTION_PIN_STEP =
  'DEVICE_AUTHENTICATION_ENCRYPTION_PIN_STEP';
export const DEVICE_PRIVATE_KEY_QR_CODE_STEP =
  'DEVICE_PRIVATE_KEY_QR_CODE_STEP';
export const DEVICE_PRIVATE_KEY_ENCRYPTION_PIN_STEP =
  'DEVICE_PRIVATE_KEY_ENCRYPTION_PIN_STEP';
