// Process State
export const ALL_PROCESSES_STATES = 'ALL_STATUS';
export const COMPLETED_PROCESSES_STATE = 'COMPLETED_STATUS';
export const INCOMPLETED_PROCESSES_STATE = 'INCOMPLETED_STATUS';

// Process Status
export const ALL_PROCESS_STATUS = 'ALL_PROCESS_STATUS';
export const OPEN_PROCESSES_STATUS = 'OPEN_PROCESSES_STATUS';
export const APPROVED_PROCESSES_STATUS = 'APPROVED_PROCESSES_STATUS';
export const PARTIAL_APPROVED_PROCESSES_STATUS =
  'PARTIAL_APPROVED_PROCESSES_STATUS';
export const REQUESTED_PROCESSES_STATUS = 'REQUESTED_PROCESSES_STATUS';
export const PARTIAL_REQUESTED_PROCESSES_STATUS =
  'PARTIAL_REQUESTED_PROCESSES_STATUS';

// Process Type
export const ALL_PROCESS_TYPES = 'ALL_PROCESS_TYPES';
export const PERSON_PROCESSES_TYPE = 'PERSON_PROCESSES_TYPE';
export const LOCATION_PROCESSES_TYPE = 'LOCATION_PROCESSES_TYPE';

// Process Assignee
export const ALL_PROCESS_ASSIGNEE = 'ALL_PROCESS_ASSIGNEE';
export const PROCESSES_NO_ASSIGNEE = 'PROCESSES_NO_ASSIGNEE';
