FROM node:14.17.0-alpine3.13
WORKDIR /app

ARG GIT_COMMIT
ARG GIT_VERSION
ARG NPM_CONFIG__AUTH
ENV NODE_ENV=development
ENV PORT=8080
ENV GIT_COMMIT $GIT_COMMIT
ENV GIT_VERSION $GIT_VERSION
ENV CHOKIDAR_USEPOLLING=true
ENV PUBLIC_URL=/contact-form

COPY package.json yarn.lock jsconfig.json craco.config.js ant.theme.js ./
COPY public/  ./public/
COPY src/  ./src/


EXPOSE 8080
CMD yarn install --mutex file:/usr/local/share/.cache/yarn/.yarn-mutex && yarn start
